apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-default-login
  namespace: argo
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"
---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: user-default-login
#   namespace: argo
# rules:
# - apiGroups:
#   - ""
#   - "*"
#   - "argoproj.io"
#   resources:
#   - "*"
#   verbs:
#   - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-default-login
rules:
- apiGroups:
  - ""
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: user-default-login
#   namespace: argo
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: user-default-login
# subjects:
# - kind: ServiceAccount
#   name: user-default-login
#   namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-default-login
  # namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: user-default-login
subjects:
- kind: ServiceAccount
  name: user-default-login
  namespace: argo